import { Employee } from './types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    anonymized_id: 'EMP_0001',
    Department: 'IT/IS',
    Position: 'Software Engineer',
    risk_score: 0.812,
    risk_level: 'High',
    top_reason_1: 'EmpSatisfaction',
    top_reason_2: 'Absences',
    top_reason_3: 'salary_vs_dept_mean',
    recommended_action: 'HR check-in / satisfaction interview | Wellbeing or flexibility discussion | Compensation review',
    nlp_advisory: 'negative feedback tone | transfer request on file',
  },
  {
    anonymized_id: 'EMP_0002',
    Department: 'Production',
    Position: 'Production Technician I',
    risk_score: 0.743,
    risk_level: 'High',
    top_reason_1: 'EngagementSurvey',
    top_reason_2: 'DaysLateLast30',
    top_reason_3: 'tenure_years',
    recommended_action: 'Manager discussion / project reassignment | Wellbeing or flexibility discussion | Career development milestone review',
    nlp_advisory: 'departure intent in feedback',
  },
  {
    anonymized_id: 'EMP_0003',
    Department: 'Sales',
    Position: 'Area Sales Manager',
    risk_score: 0.681,
    risk_level: 'High',
    top_reason_1: 'salary_vs_dept_mean',
    top_reason_2: 'EmpSatisfaction',
    top_reason_3: 'SpecialProjectsCount',
    recommended_action: 'Compensation review | HR check-in / satisfaction interview | Assign meaningful stretch projects',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0004',
    Department: 'IT/IS',
    Position: 'Data Analyst',
    risk_score: 0.524,
    risk_level: 'Medium',
    top_reason_1: 'engagement_x_satisfaction',
    top_reason_2: 'Absences',
    top_reason_3: 'age',
    recommended_action: 'HR check-in / engagement improvement plan | Wellbeing or flexibility discussion | Age-appropriate retention strategy',
    nlp_advisory: 'negative feedback tone',
  },
  {
    anonymized_id: 'EMP_0005',
    Department: 'Admin Offices',
    Position: 'Administrative Assistant',
    risk_score: 0.487,
    risk_level: 'Medium',
    top_reason_1: 'EmpSatisfaction',
    top_reason_2: 'tenure_years',
    top_reason_3: 'Salary',
    recommended_action: 'HR check-in / satisfaction interview | Career development milestone review | Compensation review',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0006',
    Department: 'Production',
    Position: 'Production Manager',
    risk_score: 0.412,
    risk_level: 'Medium',
    top_reason_1: 'EngagementSurvey',
    top_reason_2: 'DaysLateLast30',
    top_reason_3: '',
    recommended_action: 'Manager discussion / project reassignment | Wellbeing or flexibility discussion',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0007',
    Department: 'IT/IS',
    Position: 'Systems Administrator',
    risk_score: 0.198,
    risk_level: 'Low',
    top_reason_1: 'tenure_years',
    top_reason_2: '',
    top_reason_3: '',
    recommended_action: 'Career development milestone review',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0008',
    Department: 'Sales',
    Position: 'Sales Representative',
    risk_score: 0.154,
    risk_level: 'Low',
    top_reason_1: 'SpecialProjectsCount',
    top_reason_2: '',
    top_reason_3: '',
    recommended_action: 'Assign meaningful stretch projects',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0009',
    Department: 'Admin Offices',
    Position: 'HR Manager',
    risk_score: 0.112,
    risk_level: 'Low',
    top_reason_1: 'age',
    top_reason_2: '',
    top_reason_3: '',
    recommended_action: 'Age-appropriate retention strategy',
    nlp_advisory: '',
  },
  {
    anonymized_id: 'EMP_0010',
    Department: 'Production',
    Position: 'Production Technician II',
    risk_score: 0.087,
    risk_level: 'Low',
    top_reason_1: 'EngagementSurvey',
    top_reason_2: '',
    top_reason_3: '',
    recommended_action: 'Monitor and follow-up',
    nlp_advisory: '',
  },
];
