from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np
import os

app = Flask(__name__)
CORS(app)  # Allow requests from Expo/React Native web

BASE = os.path.dirname(os.path.abspath(__file__))


def _load_api_key() -> str | None:
    """Load optional API key.

    Priority:
    1) env var HR_ATTRITION_API_KEY
    2) file api/api_key.txt (generated by the notebook)

    If no key is found, the API stays open (hackathon-friendly default).
    """
    env_key = os.environ.get('HR_ATTRITION_API_KEY')
    if env_key and env_key.strip():
        return env_key.strip()

    try:
        path = os.path.join(BASE, 'api_key.txt')
        with open(path, 'r', encoding='utf-8') as f:
            file_key = f.read().strip()
        return file_key or None
    except FileNotFoundError:
        return None


API_KEY = _load_api_key()


def _require_api_key():
    """Return a Flask response tuple if unauthorized; otherwise None."""
    if not API_KEY:
        return None

    provided = request.headers.get('X-API-Key') or request.args.get('api_key')
    if not provided or provided != API_KEY:
        return jsonify({'error': 'Unauthorized'}), 401
    return None

def load(name):
    return joblib.load(os.path.join(BASE, name))

try:
    model             = load('model.pkl')
    FEATURE_COLS      = load('feature_cols.pkl')
    label_encoders    = load('label_encoders.pkl')
    scaler            = load('scaler.pkl')
    best_model_name   = load('best_model_name.pkl')
    feature_medians   = load('feature_medians.pkl')
    dept_mean_salaries = load('dept_mean_salaries.pkl')
    encoder_classes   = load('encoder_classes.pkl')
    OVERALL_MEAN_SALARY = float(np.mean(list(dept_mean_salaries.values())))
    MODEL_READY = True
    print(f"[API] Model loaded: {best_model_name}")
    print(f"[API] {len(FEATURE_COLS)} features")
    print(f"[API] Departments: {list(dept_mean_salaries.keys())}")
except FileNotFoundError as e:
    MODEL_READY = False
    print(f"[API] WARNING — model artifacts not found: {e}")
    print("[API] Run the notebook fully (last cell) to generate artifacts.")


@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok' if MODEL_READY else 'no_model', 'model': best_model_name if MODEL_READY else None})


@app.route('/categories', methods=['GET'])
def categories():
    """Return valid values for each categorical field."""
    unauthorized = _require_api_key()
    if unauthorized is not None:
        return unauthorized
    if not MODEL_READY:
        return jsonify({'error': 'Model not loaded'}), 503
    return jsonify(encoder_classes)


@app.route('/predict', methods=['POST'])
def predict():
    unauthorized = _require_api_key()
    if unauthorized is not None:
        return unauthorized
    if not MODEL_READY:
        return jsonify({'error': 'Model not loaded — run the notebook export cell first'}), 503

    data = request.get_json(force=True)

    # Start from training medians (safe defaults for all features)
    features = dict(feature_medians)

    # ── Direct numeric mappings ──────────────────────────────────────────
    numeric_map = {
        'age':                        'age',
        'tenure_years':               'tenure_years',
        'salary':                     'Salary',
        'engagement_survey':          'EngagementSurvey',
        'emp_satisfaction':           'EmpSatisfaction',
        'special_projects_count':     'SpecialProjectsCount',
        'days_late_last_30':          'DaysLateLast30',
        'absences':                   'Absences',
        'has_transfer_request':       'has_transfer_request',
        'transfer_request_sentiment': 'transfer_request_sentiment',
        'feedback_sentiment':         'feedback_sentiment',
        'feedback_has_compensation':  'feedback_has_compensation',
        'feedback_has_growth':        'feedback_has_growth',
        'feedback_has_workload':      'feedback_has_workload',
        'feedback_has_management':    'feedback_has_management',
        'feedback_has_departure_intent': 'feedback_has_departure_intent',
        'days_since_review':          'days_since_review',
    }
    for api_key, feat_key in numeric_map.items():
        val = data.get(api_key)
        if val is not None:
            features[feat_key] = float(val)

    # ── Categorical encodings ─────────────────────────────────────────────
    cat_defaults = {
        'Department':       'Production',
        'Position':         'Production Technician I',
        'MaritalDesc':      'Single',
        'CitizenDesc':      'US Citizen',
        'RecruitmentSource': 'Indeed',
        'PerformanceScore': 'Fully Meets',
    }
    for col, default in cat_defaults.items():
        val = data.get(col, default)
        le = label_encoders.get(col)
        if le is None:
            continue
        # If value not seen in training, fall back to default
        if val not in encoder_classes.get(col, []):
            val = default
        features[col + '_enc'] = float(le.transform([val])[0])

    # ── Derived / composite features ──────────────────────────────────────
    salary = features.get('Salary', OVERALL_MEAN_SALARY)
    department = data.get('Department', cat_defaults['Department'])
    dept_mean = dept_mean_salaries.get(department, OVERALL_MEAN_SALARY)
    features['salary_vs_dept_mean'] = salary / dept_mean if dept_mean > 0 else 1.0

    eng = features.get('EngagementSurvey', 3.0)
    sat = features.get('EmpSatisfaction', 3.0)
    features['engagement_x_satisfaction'] = eng * sat

    # ── Build ordered feature vector ──────────────────────────────────────
    X = np.array([[features.get(col, feature_medians.get(col, 0.0)) for col in FEATURE_COLS]])

    # Scale only if Logistic Regression (RF and XGBoost don't need it;
    # CalibratedClassifierCV wraps the base estimator so scaling was done
    # at fit time for LR — we still need to scale the input for LR)
    if best_model_name == 'Logistic Regression':
        X = scaler.transform(X)

    # ── Predict ───────────────────────────────────────────────────────────
    prob = float(model.predict_proba(X)[0][1])
    risk_level = 'Élevé' if prob >= 0.6 else 'Moyen' if prob >= 0.3 else 'Faible'

    return jsonify({
        'score':      round(prob, 4),
        'risk_level': risk_level,
        'model':      best_model_name,
    })


if __name__ == '__main__':
    print("[API] Starting Flask API on http://localhost:5000")
    app.run(debug=False, port=5000)
